### ISSUE TITLE
Missing keys in Trie

### ISSUE THREAD

**Issue by emilbayes** [JuliaLang/DataStructures.jl#101]
I'm trying to load one of the default dictionaries on OS X into a Trie, but some keys seem to go missing, and I can't work out the pattern. Here's an example:

```julia
#pr-test.jl
using DataStructures

tokenDictionary = Trie{Nothing}()

for token in eachline(STDIN)
  tokenDictionary[lowercase(strip(token))] = Nothing()
end

for k in sort(collect(keys(tokenDictionary)))
  println(k)
end
```

Run with the following command:

```bash
cat /usr/share/dict/words \
   | julia pr-test.jl \
   | diff -i /usr/share/dict/words -
```

I'm using DataStructures `0.3.9` and Julia `0.3.8`. The `diff` only shows keys missing from the Julia Trie, not the other way. Am I doing something wrong?

**Comment by kmsquire** [comment]
Sorry it took so long for anyone to get back to you.  

If you add a "-y" to the diff output, it would make it clear what's happening: All of the keys that are missing  have both a capitalized and an uncapitalized version in the dictionary, and since you call `lowercase` on the input, only one of them is kept.  So you're getting the correct output.

As an aside, `Nothing() === nothing`, and for some reason, in Julia v0.4, `Nothing()` produces an error.  I'm not sure it should, but you should probably use `nothing` instead.

Cheers!
