### ISSUE TITLE
keys don't seem to be properly typed

### ISSUE THREAD

**Issue by atteson** [JuliaLang/DataStructures.jl#103]
When I run "typeof(collect(keys(SortedDict( Dict( ["a","b","c"], [1,2,3] ) ))))", I get "Array{Any,1}" whereas I would expect to get "Array{ASCIIString,1}" which is what "typeof(collect(keys(SortedDict( Dict( ["a","b","c"], [1,2,3] ) ))))" gives me.

I'm using Julia version 0.3.8 and seem to be on commit 79e517 of the DataStructures package.

**Comment by kmsquire** [comment]
Cc: @StephenVavasis

**Comment by StephenVavasis** [comment]
Thanks for pointing out this omission.  I have fixed this in the latest commit in the SortedContainers branch, which will, in the near future, become the master branch.  You can find this commit in my personal repository.  In the mean time, you can also work around this problem by using the two-argument form of the 'collect' function: collect(T, itr)

**Comment by kmsquire** [comment]
@StephenVavasis, thanks for fixing this.  

Generally, the preferable action would be to submit a separate, small pull request containing just this fix (against master).  Is that something you would be willing to do?  

You would then have to rebase your SortedContainers branch agains master (which you'll have to do before it is merged anyway.)

**Comment by StephenVavasis** [comment]
Kevin,

I just submitted a pull request that fixes just this one issue

**Comment by StephenVavasis** [comment]
This patch that I just submitted (#106) address the issue that keys and values objects for SortedDict ought to support other functions besides just start/done/next in order to be compatible with Dict.  In particular, the patch addresses the problem that keys and values objects previously didn't support ``collect`` correctly.   

I'm studying dict.jl, and I see that there is at least one other function that ``keys`` is supposed to support but that it currently does not.

```julia
    in(k, keys(s))
```
where s is a SortedDict, will be slow because this operation will be done in the naive way (iterate over all keys of s, see if k is one of them).  The haskey() function is ok -- it uses efficient key lookup.

Fixing this is more complicated, because it is not clear what in(k, keys(a:b)) ought to do, where a, b are tokens.  (In the SortedContainers branch, this would b in(k, keys(inclusive(s,a,b))), where a, b are semitokens.)

There are several possibilities:

(1) Leave the code alone, but in the documentation, advise against using in(k,keys(..)).  This would contradict the Julia manual, which says that in(k,keys(..)) is the same as haskey(..).

(2) Make in(k,keys(s)) behave the smart way, but in(k,keys( subrange ) behave the slow way.

(3) Write a bunch of new code to support in(k,keys( subrange  )) efficiently.  This seems like a waste of time, since this call would be rarely used.

A second issue is: should I fix this in the master branch as well as my planned release SortedContainers branch or just in the planned release SortedContainers?

**Comment by ScottPJones** [comment]
What about 2c) Make `in(k, keys(s))` behave the smart way, but `in(k, keys(subrange))` behaves the slow way, but warn about the performance issue in the documentation?`  (BTW, I like very much that you put timing information in the documentation)

**Comment by kmsquire** [comment]
Regarding the second issue: at this point, my preference is to push to get #88 submitted, and have this go in as a separate PR.  I'm going to make another request for another set of eyes to review it.  If I get someone, great.  If not, I'll ask you to squash, and merge.

**Comment by kmsquire** [comment]
Seems to have been fixed, probably by #113.
