### ISSUE TITLE
merge of OrderedDict's fails in v.0.4; produces Dict; works ok in v.0.3.11

### ISSUE THREAD

**Issue by montyvesselinov** [JuliaLang/DataStructures.jl#127]
julia> d
DataStructures.OrderedDict{Char,Int64} with 1 entry:
  'a' => 1

julia> c
DataStructures.OrderedDict{ASCIIString,Int64} with 2 entries:
  "b" => 1
  "d" => 4

julia> merge(d,c)
Dict{Any,Int64} with 3 entries:
  "b" => 1
  'a' => 1
  "d" => 4

**Comment by danielarndt** [comment]
It seems the returning of a Dict instead of a OrderedDict is caused by this commit in Julia: https://github.com/JuliaLang/julia/commit/ebbf1ddc99b240924bdef14b7a87500b5c4c989b

Essentially, the merge function has been made to promote types where appropriate, but by doing so needs to re-initialize the `Associative` (without doing some runtime-evaluation and compiling I'm not sure how you reconstruct the type, with different keys). I assume they chose to initialize this as a Dict to keep things simple.

I believe the Julian way of fixing this downstream is to overload with a more specific function. I put up a pull request that addresses this (#143) , and would love any feedback.

```
using DataStructures
d = OrderedDict(Char, Int64)
d['a'] = 1

c = OrderedDict(ASCIIString, Int64)
c["b"] = 1
c["d"] = 4
```
```
julia> d
DataStructures.OrderedDict{Char,Int64} with 1 entry:
  'a' => 1

julia> c
DataStructures.OrderedDict{ASCIIString,Int64} with 2 entries:
  "b" => 1
  "d" => 4

julia> merge(d,c)
DataStructures.OrderedDict{Any,Int64} with 3 entries:
  'a' => 1
  "b" => 1
  "d" => 4
```
