### ISSUE TITLE
eachindex() not implemented for SortedDict, SortedMultiDict

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/DataStructures.jl#130]
The new iteration function eachindex() is not implemented for SortedDict or SortedMultiDict.  There is a problem in appropriately implementing it.  For SortedDict, there are two separate getindex functions, the first being `sd[k]`, where k is a key, and the second being `sd[s]`, where s is a semitoken.  It is not clear which type of index should be returned by eachindex().  For SortedMultiDict, there is only `smd[s]` (where s is a semitoken).  On the other hand, for Dict, there is only `d[k]` (where k is a key).  So the problem is that if eachindex() were implemented for SortedDict and SortedMultiDict, then either 

(1) eachindex() for SortedDict would return semitokens and be inconsistent with eachindex() for Dict

or

(2) eachindex() for SortedDict would return keys and be inconsistent with eachindex() for SortedMultiDict.

Both of these choices seem like they would surprise the user, so I think the best choice is not to implement eachindex() at all.

Unless a big discussion starts, I'll close this issue in a week or so.

**Comment by ScottPJones** [comment]
I'd prefer `eachindex` to work over the keys for `SortedDict`.
A `SortedDict` still acts the same as a `Dict`, it just has the added property of being sorted, just like an `OrderedDict` acts like a `Dict`, but maintains insertion order.

`SortedMultiDict` is the one that is rather different - and I don't think that having `eachindex` act differently or not be implemented for SMD would be that much of a surprise.
In my previous life, everything was a multi-dimensional sorted associative array (i.e. nested `SortedDict`s), so it was never necessary to have a special `SortedMultiDict`, because if you needed to store multiple things at each key at a level, you'd simply put them at a lower subscript level.

**Comment by StephenVavasis** [comment]
I decided to implement ``eachindex()`` for ``SortedDict`` to match ``Dict`` as suggested by @ScottPJones.  For ``SortedSet`` and ``SortedMultiDict``, ``eachindex()`` loops over semitokens.  This is now merged in the latest master.
