### ISSUE TITLE
Add Binary Trees / Red-black trees

### ISSUE THREAD

**Issue by rawls238** [JuliaLang/DataStructures.jl#154]
seem like pretty standard data structures that this package should include - any reason against including them?

**Comment by StephenVavasis** [comment]
The package already includes 2-3 trees; these are the basis for SortedDict, SortedMultiDict, and SortedSet.  AFAIK, red-black trees are functionally equivalent to 2-3 trees but may offer a slight performance boost.  If you would like to try to implement red-black trees, then you could experiment to see if they are any better than 2-3 trees.

In my opinion, a preferable option, if you have the time, is to implement cache-oblivious B-trees (see the SIAM J. Comput, Bender et al).  My limited performance study on my Julia 2-3 trees seems to indicate that the biggest performance problem is caused by cache misses.  I have a long-term plan to implement the Bender et al technique myself, but I won't get to it in the near future.

**Comment by rawls238** [comment]
ah I see it now - may be good to mention that it's included in the package in the docs.

Also I may give implementing the cache-oblivious trees a shot.

Regardless, I think this can be closed since I originally couldn't find any sort of tree implementation in this package.
